---
blueprint_path: /Users/brvy/code/golang/empires-of-avalon/blueprints
postgres:
  user: "postgres"
  password: "example"
  host: "127.0.0.1"
  port: "5432"
  database: "postgres"
  sslmode: "disable"
cluster:
  name: "avalond-dev"
  node:
    host: "127.0.0.1"
    port: 52479
http:
  address: "0.0.0.0"
  port: "3000"
etcd:
  endpoints:
    - 127.0.0.1:22379
  root: "avalond-dev"
nats:
  host: 127.0.0.1
  port: 4222
  user: ""
  password: ""
logging:
  level: debug
instrumentation:
  traces:
    endpoint: localhost:4318
    insecure: true
registry:
  remote_kind: etcd