version: '3'

services:
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
  roach:
    image: cockroachdb/cockroach:v22.1.10
    ports:
      - 26257:26257
      - 8088:8080
    volumes:
      - roach-data:/cockroach/cockroach-data
      - ./init/:/docker-entrypoint-initdb.d/
    command: "start-single-node --insecure"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
    ports:
      - 22379:2379
      - 22380:2380
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4318:4318
      - 14269:14269

volumes:
  roach-data:
    driver: local
  etcd_data:
    driver: local
