version: '3'

services:
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
  psql:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
    ports:
      - 22379:2379
      - 22380:2380
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4318:4318
      - 14269:14269

volumes:
  roach-data:
    driver: local
  etcd_data:
    driver: local
