apiVersion: v1
kind: ConfigMap
metadata:
    name: avalond-config-file
data:
    config.yaml: |
        postgres:
            user: "postgres"
            password: "QV_F<TMK0=)}/6nl[[7pdklP"
            host: "avalond-prod-primary.avalond.svc"
            port: "5432"
            database: "postgres"
            sslmode: "disable"
        cluster:
            name: "avalond-dev"
            node:
                host: "127.0.0.1"
                port: "52479"
        http:
            address: "0.0.0.0"
            port: "3000"
        etcd:
            endpoints:
                - avalond-etcd-0.avalond.svc.cluster.local:22379
            root: "avalond"
        nats:
            host: avalond-nats-0.avalond.svc.cluster.local
            port: 4222
            user: ""
            password: ""
        logging:
            level: debug