apiVersion: v1
kind: ConfigMap
metadata:
    name: avalond-config-file
data:
    config.yaml: |
        postgres:
            user: "postgres"
            host: "avalond-prod-primary.avalond.svc"
            port: "5432"
            database: "postgres"
            sslmode: "disable"
        cluster:
            name: "avalond-dev"
            node:
                host: "127.0.0.1"
                port: "52479"
        http:
            address: "0.0.0.0"
            port: "3000"
        etcd:
            endpoints:
                - avalond-etcd.avalond.svc.cluster.local:2379
            root: "avalond"
            user: "root"
        nats:
            host: avalond-nats.avalond.svc.cluster.local
            port: 4222
        logging:
            level: debug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avalond-psql-init
data:
  init.sql: |-
    CREATE TABLE snapshots (
        kind varchar(255) not null,
        identity uuid not null,
        data blob not null,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE blueprints (
        id uuid not null,
        kind varchar(255) not null,
        data json not null,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );