apiVersion: v1
kind: ConfigMap
metadata:
    name: avalond-config-file
data:
    config.yaml: |
        blueprint_path: /opt/blueprints
        postgres:
            user: "postgres"
            host: "avalond-prod-primary.avalond.svc"
            port: "5432"
            database: "postgres"
            sslmode: "disable"
        cluster:
            name: "avalond-dev"
            node:
                host: "127.0.0.1"
                port: "52479"
        http:
            address: "0.0.0.0"
            port: "3000"
        etcd:
            endpoints:
                - avalond-etcd.avalond.svc.cluster.local:2379
            root: "avalond"
            user: "root"
        nats:
            host: avalond-nats.avalond.svc.cluster.local
            port: 4222
        logging:
            level: info
        instrumentation:
            traces:
                endpoint: valhalla-tempo.valhalla.svc.cluster.local:4318
                insecure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: avalond-blueprints
data:
    buildings.yaml: |
        ---
        kind: Building
        name: House
        build_time: 10s
        initial_amount: 1
        cost:
          - resource: Wood
            amount: 20
            permanent: true
          - resource: Population
            amount: 2
            permanent: false
        generates:
          - name: Population
            amount: 1
            tick_length: 2s
        stores:
          Population: 6
        ---
        kind: Building
        name: Warehouse
        build_time: 10s
        initial_amount: 1
        cost:
          - resource: Wood
            amount: 50
            permanent: true
          - resource: Population
            amount: 5
            permanent: false
        stores:
          Wood: 100
          Stone: 100
          Planks: 40
        ---
        kind: Building
        name: Woodcutter
        build_time: 10s
        workers_maximum: 2
        cost:
          - resource: Wood
            amount: 30
            permanent: true
          - resource: Population
            amount: 3
            permanent: false
        generates:
          - name: Wood
            amount: 3
            tick_length: 20s
        ---
        kind: Building
        name: Lumberyard
        build_time: 10s
        workers_maximum: 2
        cost:
          - resource: Wood
            amount: 50
            permanent: true
          - resource: Population
            amount: 3
            permanent: false
        transforms:
          - name: Planks
            cost:
              - resource: Wood
                amount: 5
                temporary: false
            result:
              - resource: Planks
                amount: 1
                tick_length: 10s
    resources.yaml: |
        ---
        kind: Resource
        name: Population
        starting_cap: 6
        starting_amount: 6
        cap_formula: |
            return buildings.house*6
        ---
        kind: Resource
        name: Wood
        starting_cap: 100
        starting_amount: 100
        cap_formula: |
            return buildings.warehouse*100
        ---
        kind: Resource
        name: Stone
        starting_cap: 100
        starting_amount: 0
        cap_formula: |
            return buildings.warehouse*100
        ---
        kind: Resource
        name: Planks
        starting_cap: 100
        starting_amount: 0
        cap_formula: |
            return buildings.warehouse*100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avalond-psql-init
data:
  init.sql: |-
    CREATE TABLE snapshots (
        kind varchar(255) not null,
        identity uuid not null,
        data bytea not null,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE blueprints (
        id uuid not null,
        kind varchar(255) not null,
        data json not null,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );