apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalond
  labels:
    app: avalond
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalond
  template:
    metadata:
      labels:
        app: avalond
    spec:
      containers:
        - name: avalon-backend
          image: alfreddobradi/avalond:v0.2.0
          ports:
            - containerPort: 3000
          command:
            - /bin/sh
            - "-c"
            - "sleep infinity"
          env:
            - name: AVALOND_PG_Passwd
              valueFrom:
                secretKeyRef:
                  name: avalond-prod-pguser-postgres
                  key: password
            - name: AVALOND_NATS_PASSWORD
              value: ""
          volumeMounts:
            - name: config
              mountPath: "/etc/avalond"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: avalond-config-file
      # - name: avalon-backend
      #   image: alfreddobradi/avalond:v0.2.0
      #   ports:
      #   - containerPort: 3000