apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalond
  labels:
    app: avalond
    app.kubernetes.io/name: avalond
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avalond
  template:
    metadata:
      labels:
        app: avalond
        app.kubernetes.io/name: avalond
      annotations:
        config.linkerd.io/skip-outbound-ports: "8200"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "avalond-reader"
        vault.hashicorp.com/agent-inject-secret-config: "avalond/env"
        vault.hashicorp.com/agent-inject-template-config: |-
          {{`{{- with secret "avalond/env" -}}
            {{ range $k, $v := .Data.data }}
                export {{ $k }}="{{ $v }}"
            {{ end }}
          {{- end -}}`}}
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ .name }}
      {{- end }}
      containers:
        - name: avalond
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c']
          args: ['. /vault/secrets/config && env && avalond']
          ports:
            - containerPort: 3000
          # envFrom:
          #   - secretRef:
          #       name: avalond-prod-auth0-config
          env:
            - name: AD_POSTGRES_PASSWD
              valueFrom:
                secretKeyRef:
                  name: avalond-prod-pguser-postgres
                  key: password
          volumeMounts:
            - name: avalond-config
              mountPath: "/etc/avalond"
              readOnly: true
            - name: avalond-blueprints
              mountPath: "/opt/blueprints"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: avalond-config
          configMap:
            name: avalond-config-file
        - name: avalond-blueprints
          configMap:
            name: avalond-blueprints
