{{ if .Values.postgresql.enabled }}
---
# Source: postgrescluster/templates/postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: avalond-prod
spec:
  postgresVersion: 15
  instances:
    - name: "avalond-prod-1"
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostssl all all all md5"
          - "hostnossl all all all md5"
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "10Gi"
  users:
    - name: postgres
  imagePullPolicy: "Always"
{{ end }}