apiVersion: v1
kind: Service
metadata:
  name: avalon-daemon
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app.kubernetes.io/name: avalond
  ports:
    - name: http
      protocol: TCP
      port: 8443
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 2223
      targetPort: 2223