// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Buildings struct {
	House      *InventoryBuilding `json:"house,omitempty"`
	Warehouse  *InventoryBuilding `json:"warehouse,omitempty"`
	Woodcutter *InventoryBuilding `json:"woodcutter,omitempty"`
}

type Inventory struct {
	User      *User                `json:"user,omitempty"`
	Buildings []*InventoryBuilding `json:"buildings,omitempty"`
	Resources []*InventoryResource `json:"resources,omitempty"`
}

type InventoryBuilding struct {
	Name   *string `json:"name,omitempty"`
	Amount *int    `json:"amount,omitempty"`
	Queue  *int    `json:"queue,omitempty"`
	Finish *string `json:"finish,omitempty"`
}

type InventoryResource struct {
	Name     *string `json:"name,omitempty"`
	Amount   *int    `json:"amount,omitempty"`
	Cap      *int    `json:"cap,omitempty"`
	Reserved *int    `json:"reserved,omitempty"`
}

type Resources struct {
	Population *InventoryResource `json:"population,omitempty"`
	Wood       *InventoryResource `json:"wood,omitempty"`
	Planks     *InventoryResource `json:"planks,omitempty"`
	Stone      *InventoryResource `json:"stone,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
