image:
  repository: alfreddobradi/avalond
  pullPolicy: Always

postgresql:
  enabled: true
nats:
  enabled: false
etcd:
  enabled: true
  auth:
    rbac:
      existingSecret: avalond-prod-etcd
      existingSecretPasswordKey: etcd-root-password