image:
  repository: artifacts.dashboards.0x42.in/docker/avalond
  pullPolicy: Always

serviceAccount:
  name: avalond
postgresql:
  enabled: true
nats:
  enabled: true
  auth:
    enabled: false
etcd:
  enabled: true
  auth:
    rbac:
      existingSecret: avalond-prod-etcd
      existingSecretPasswordKey: etcd-root-password