name: Docker Image CI

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  lint:

      runs-on: ubuntu-latest
      steps:
        - 
          name: Checkout
          uses: actions/checkout@v3
        - 
          name: Go Setup
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            cache: false
        - 
          name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.53
            args: --out-format=github-actions

  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Go Setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      -
        name: Run tests
        run: go test -count=1 ./...

  build:
    if: github.ref == 'refs/heads/"main"' && github.event_name == 'release'

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/avalond:latest,${{ secrets.DOCKERHUB_USERNAME }}/avalond:${{ github.event.release.tag_name }}

